#############################################################################
# Makefile for building: SMPlayer
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 5? 22 10:45:03 2013
# Project:  SMPlayer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile SMPlayer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/phonon -I/usr/include -I/usr/include/phonon_compat -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lphonon -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		imageprocessor.cpp \
		centralwidget.cpp \
		pixitem.cpp \
		scanwidget.cpp moc_imageprocessor.cpp \
		moc_centralwidget.cpp \
		moc_scanwidget.cpp
OBJECTS       = main.o \
		imageprocessor.o \
		centralwidget.o \
		pixitem.o \
		scanwidget.o \
		moc_imageprocessor.o \
		moc_centralwidget.o \
		moc_scanwidget.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		SMPlayer.pro
QMAKE_TARGET  = SMPlayer
DESTDIR       = 
TARGET        = SMPlayer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SMPlayer.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile SMPlayer.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/debug.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile SMPlayer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SMPlayer1.0.0 || $(MKDIR) .tmp/SMPlayer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SMPlayer1.0.0/ && $(COPY_FILE) --parents imageprocessor.h centralwidget.h pixitem.h scanwidget.h .tmp/SMPlayer1.0.0/ && $(COPY_FILE) --parents main.cpp imageprocessor.cpp centralwidget.cpp pixitem.cpp scanwidget.cpp .tmp/SMPlayer1.0.0/ && (cd `dirname .tmp/SMPlayer1.0.0` && $(TAR) SMPlayer1.0.0.tar SMPlayer1.0.0 && $(COMPRESS) SMPlayer1.0.0.tar) && $(MOVE) `dirname .tmp/SMPlayer1.0.0`/SMPlayer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SMPlayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_imageprocessor.cpp moc_centralwidget.cpp moc_scanwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_imageprocessor.cpp moc_centralwidget.cpp moc_scanwidget.cpp
moc_imageprocessor.cpp: centralwidget.h \
		pixitem.h \
		scanwidget.h \
		imageprocessor.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) imageprocessor.h -o moc_imageprocessor.cpp

moc_centralwidget.cpp: pixitem.h \
		scanwidget.h \
		centralwidget.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) centralwidget.h -o moc_centralwidget.cpp

moc_scanwidget.cpp: pixitem.h \
		scanwidget.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) scanwidget.h -o moc_scanwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp imageprocessor.h \
		centralwidget.h \
		pixitem.h \
		scanwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

imageprocessor.o: imageprocessor.cpp imageprocessor.h \
		centralwidget.h \
		pixitem.h \
		scanwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageprocessor.o imageprocessor.cpp

centralwidget.o: centralwidget.cpp centralwidget.h \
		pixitem.h \
		scanwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centralwidget.o centralwidget.cpp

pixitem.o: pixitem.cpp pixitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixitem.o pixitem.cpp

scanwidget.o: scanwidget.cpp scanwidget.h \
		pixitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanwidget.o scanwidget.cpp

moc_imageprocessor.o: moc_imageprocessor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageprocessor.o moc_imageprocessor.cpp

moc_centralwidget.o: moc_centralwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_centralwidget.o moc_centralwidget.cpp

moc_scanwidget.o: moc_scanwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scanwidget.o moc_scanwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

